/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Staff1RouteImport } from './routes/staff1'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OptionsRouteImport } from './routes/options'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as BestSellerRouteImport } from './routes/best-seller'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SearchPackageIdRouteImport } from './routes/search.$packageId'
import { Route as PackagePackageIdRouteImport } from './routes/package.$packageId'
import { Route as ContactPageRouteImport } from './routes/contact.page'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminProfilesRouteImport } from './routes/admin.profiles'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminDestinationsRouteImport } from './routes/admin.destinations'

const Staff1Route = Staff1RouteImport.update({
  id: '/staff1',
  path: '/staff1',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsRoute = OptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellerRoute = BestSellerRouteImport.update({
  id: '/best-seller',
  path: '/best-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SearchPackageIdRoute = SearchPackageIdRouteImport.update({
  id: '/$packageId',
  path: '/$packageId',
  getParentRoute: () => SearchRoute,
} as any)
const PackagePackageIdRoute = PackagePackageIdRouteImport.update({
  id: '/package/$packageId',
  path: '/package/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactPageRoute = ContactPageRouteImport.update({
  id: '/contact/page',
  path: '/contact/page',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/best-seller': typeof BestSellerRoute
  '/destinations': typeof DestinationsRoute
  '/options': typeof OptionsRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRouteWithChildren
  '/staff1': typeof Staff1Route
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/contact/page': typeof ContactPageRoute
  '/package/$packageId': typeof PackagePackageIdRoute
  '/search/$packageId': typeof SearchPackageIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-seller': typeof BestSellerRoute
  '/destinations': typeof DestinationsRoute
  '/options': typeof OptionsRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRouteWithChildren
  '/staff1': typeof Staff1Route
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/contact/page': typeof ContactPageRoute
  '/package/$packageId': typeof PackagePackageIdRoute
  '/search/$packageId': typeof SearchPackageIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/best-seller': typeof BestSellerRoute
  '/destinations': typeof DestinationsRoute
  '/options': typeof OptionsRoute
  '/packages': typeof PackagesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRouteWithChildren
  '/staff1': typeof Staff1Route
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/staff': typeof AdminStaffRoute
  '/contact/page': typeof ContactPageRoute
  '/package/$packageId': typeof PackagePackageIdRoute
  '/search/$packageId': typeof SearchPackageIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/best-seller'
    | '/destinations'
    | '/options'
    | '/packages'
    | '/profile'
    | '/search'
    | '/staff1'
    | '/admin/destinations'
    | '/admin/enquiries'
    | '/admin/packages'
    | '/admin/profiles'
    | '/admin/staff'
    | '/contact/page'
    | '/package/$packageId'
    | '/search/$packageId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/best-seller'
    | '/destinations'
    | '/options'
    | '/packages'
    | '/profile'
    | '/search'
    | '/staff1'
    | '/admin/destinations'
    | '/admin/enquiries'
    | '/admin/packages'
    | '/admin/profiles'
    | '/admin/staff'
    | '/contact/page'
    | '/package/$packageId'
    | '/search/$packageId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/best-seller'
    | '/destinations'
    | '/options'
    | '/packages'
    | '/profile'
    | '/search'
    | '/staff1'
    | '/admin/destinations'
    | '/admin/enquiries'
    | '/admin/packages'
    | '/admin/profiles'
    | '/admin/staff'
    | '/contact/page'
    | '/package/$packageId'
    | '/search/$packageId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BestSellerRoute: typeof BestSellerRoute
  DestinationsRoute: typeof DestinationsRoute
  OptionsRoute: typeof OptionsRoute
  PackagesRoute: typeof PackagesRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRouteWithChildren
  Staff1Route: typeof Staff1Route
  ContactPageRoute: typeof ContactPageRoute
  PackagePackageIdRoute: typeof PackagePackageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff1': {
      id: '/staff1'
      path: '/staff1'
      fullPath: '/staff1'
      preLoaderRoute: typeof Staff1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options': {
      id: '/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof OptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-seller': {
      id: '/best-seller'
      path: '/best-seller'
      fullPath: '/best-seller'
      preLoaderRoute: typeof BestSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/search/$packageId': {
      id: '/search/$packageId'
      path: '/$packageId'
      fullPath: '/search/$packageId'
      preLoaderRoute: typeof SearchPackageIdRouteImport
      parentRoute: typeof SearchRoute
    }
    '/package/$packageId': {
      id: '/package/$packageId'
      path: '/package/$packageId'
      fullPath: '/package/$packageId'
      preLoaderRoute: typeof PackagePackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/page': {
      id: '/contact/page'
      path: '/contact/page'
      fullPath: '/contact/page'
      preLoaderRoute: typeof ContactPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDestinationsRoute: typeof AdminDestinationsRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDestinationsRoute: AdminDestinationsRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SearchRouteChildren {
  SearchPackageIdRoute: typeof SearchPackageIdRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchPackageIdRoute: SearchPackageIdRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BestSellerRoute: BestSellerRoute,
  DestinationsRoute: DestinationsRoute,
  OptionsRoute: OptionsRoute,
  PackagesRoute: PackagesRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRouteWithChildren,
  Staff1Route: Staff1Route,
  ContactPageRoute: ContactPageRoute,
  PackagePackageIdRoute: PackagePackageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
